# Generated by Django 4.2.7 on 2023-11-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='body',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
